In [50]:
import numpy as np
import pandas as pd
from nltk.stem import PorterStemmer
import re
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [8]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

[nltk_data] Error loading stopwords: <urlopen error [WinError 10060] A
[nltk_data]     connection attempt failed because the connected party
[nltk_data]     did not properly respond after a period of time, or
[nltk_data]     established connection failed because connected host
[nltk_data]     has failed to respond>


In [9]:
hsdata = pd.read_csv('labeled_data.csv')

In [10]:
hsdata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24783 entries, 0 to 24782
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   Unnamed: 0          24783 non-null  int64 
 1   count               24783 non-null  int64 
 2   hate_speech         24783 non-null  int64 
 3   offensive_language  24783 non-null  int64 
 4   neither             24783 non-null  int64 
 5   class               24783 non-null  int64 
 6   tweet               24783 non-null  object
dtypes: int64(6), object(1)
memory usage: 1.3+ MB


In [11]:
hsdata.head()

Unnamed: 0  count  hate_speech  offensive_language  neither  class  \
0           0      3            0                   0        3      2   
1           1      3            0                   3        0      1   
2           2      3            0                   3        0      1   
3           3      3            0                   2        1      1   
4           4      6            0                   6        0      1   

                                               tweet  
0  !!! RT @mayasolovely: As a woman you shouldn't...  
1  !!!!! RT @mleew17: boy dats cold...tyga dwn ba...  
2  !!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...  
3  !!!!!!!!! RT @C_G_Anderson: @viva_based she lo...  
4  !!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...

In [30]:
#NLP cleaning
tweets = []
tweet = hsdata['tweet'].tolist()
ps = PorterStemmer()
i = 0
for twee in tweet:
    no_num = re.sub('[^a-zA-Z]', ' ', twee)
    lower_case = no_num.lower()
    listofwords = lower_case.split()
    after_stemming = [ps.stem(word) for word in listofwords if word not in stopwords.words('english')]
    review = ' '.join(after_stemming)
    tweets.append(review)

In [47]:
cv = CountVectorizer()
X = cv.fit_transform(tweets)
y = hsdata['class']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [48]:
mnb = MultinomialNB()
mnb.fit(X_train, y_train)

MultinomialNB()

In [49]:
y_pred = mnb.predict(X_test)

In [52]:
cm = confusion_matrix(y_test, y_pred)
cr = classification_report(y_test, y_pred)
acc = accuracy_score(y_test, y_pred)

print(cm, '\n\n', cr, '\n', acc)

[[  19  304   38]
 [  35 4679   80]
 [   6  351  684]] 

               precision    recall  f1-score   support

           0       0.32      0.05      0.09       361
           1       0.88      0.98      0.92      4794
           2       0.85      0.66      0.74      1041

    accuracy                           0.87      6196
   macro avg       0.68      0.56      0.59      6196
weighted avg       0.84      0.87      0.84      6196
 
 0.868624919302776
