In [1]:
import numpy as np
import pandas as pd
from nltk.stem import WordNetLemmatizer
import re
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [2]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\abhin\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [3]:
hsdata = pd.read_csv('labeled_data.csv')

In [4]:
hsdata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24783 entries, 0 to 24782
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   Unnamed: 0          24783 non-null  int64 
 1   count               24783 non-null  int64 
 2   hate_speech         24783 non-null  int64 
 3   offensive_language  24783 non-null  int64 
 4   neither             24783 non-null  int64 
 5   class               24783 non-null  int64 
 6   tweet               24783 non-null  object
dtypes: int64(6), object(1)
memory usage: 1.3+ MB


In [5]:
hsdata.head()

Unnamed: 0  count  hate_speech  offensive_language  neither  class  \
0           0      3            0                   0        3      2   
1           1      3            0                   3        0      1   
2           2      3            0                   3        0      1   
3           3      3            0                   2        1      1   
4           4      6            0                   6        0      1   

                                               tweet  
0  !!! RT @mayasolovely: As a woman you shouldn't...  
1  !!!!! RT @mleew17: boy dats cold...tyga dwn ba...  
2  !!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...  
3  !!!!!!!!! RT @C_G_Anderson: @viva_based she lo...  
4  !!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...

In [6]:
#NLP cleaning
tweets = []
tweet = hsdata['tweet'].tolist()
wordnet = WordNetLemmatizer()
i = 0
for twee in tweet:
    no_num = re.sub('[^a-zA-Z]', ' ', twee)
    lower_case = no_num.lower()
    listofwords = lower_case.split()
    after_lemat = [wordnet.lemmatize(word) for word in listofwords if word not in stopwords.words('english')]
    review = ' '.join(after_lemat)
    tweets.append(review)

In [24]:
cv = CountVectorizer(max_features=5000)
print(tweets)
X = cv.fit_transform(tweets)
y = hsdata['class']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

['rt mayasolovely woman complain cleaning house amp man always take trash', 'rt mleew boy dat cold tyga dwn bad cuffin dat hoe st place', 'rt urkindofbrand dawg rt sbaby life ever fuck bitch start cry confused shit', 'rt c g anderson viva based look like tranny', 'rt shenikaroberts shit hear might true might faker bitch told ya', 'madison x shit blow claim faithful somebody still fucking hoe', 'brighterdays sit hate another bitch got much shit going', 'selfiequeenbri cause tired big bitch coming u skinny girl', 'amp might get ya bitch back amp thats', 'rhythmixx hobby include fighting mariam bitch', 'keeks bitch curve everyone lol walked conversation like smh', 'murda gang bitch gang land', 'hoe smoke loser yea go ig', 'bad bitch thing like', 'bitch get', 'bitch nigga miss', 'bitch plz whatever', 'bitch love', 'bitch get cut everyday b', 'black bottle amp bad bitch', 'broke bitch cant tell nothing', 'cancel bitch like nino', 'cant see hoe wont change', 'fuck bitch dont even suck dick k

In [8]:
mnb = MultinomialNB()
mnb.fit(X_train, y_train)

MultinomialNB()

In [9]:
y_pred = mnb.predict(X_test)

In [10]:
cm = confusion_matrix(y_test, y_pred)
cr = classification_report(y_test, y_pred)
acc = accuracy_score(y_test, y_pred)

print(cm, '\n\n', cr, '\n', acc)

[[  93  225   43]
 [ 106 4573  115]
 [  27  212  802]] 

               precision    recall  f1-score   support

           0       0.41      0.26      0.32       361
           1       0.91      0.95      0.93      4794
           2       0.84      0.77      0.80      1041

    accuracy                           0.88      6196
   macro avg       0.72      0.66      0.68      6196
weighted avg       0.87      0.88      0.87      6196
 
 0.8825048418334409


In [23]:
bad_words_from_domini = ['mofo', 'i am a bitch']

In [25]:
X = cv.transform(bad_words_from_domini).toarray()
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [26]:
print(mnb.predict(X))

[1 1]
