In [72]:
import numpy as np
import pandas as pd
from nltk.stem import WordNetLemmatizer
import re
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [73]:
# import nltk
# nltk.download('stopwords')
from nltk.corpus import stopwords

In [74]:
hsdata = pd.read_csv('labeled_data.csv')

In [75]:
hsdata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24783 entries, 0 to 24782
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   Unnamed: 0          24783 non-null  int64 
 1   count               24783 non-null  int64 
 2   hate_speech         24783 non-null  int64 
 3   offensive_language  24783 non-null  int64 
 4   neither             24783 non-null  int64 
 5   class               24783 non-null  int64 
 6   tweet               24783 non-null  object
dtypes: int64(6), object(1)
memory usage: 1.3+ MB


In [76]:
hsdata.head()

Unnamed: 0  count  hate_speech  offensive_language  neither  class  \
0           0      3            0                   0        3      2   
1           1      3            0                   3        0      1   
2           2      3            0                   3        0      1   
3           3      3            0                   2        1      1   
4           4      6            0                   6        0      1   

                                               tweet  
0  !!! RT @mayasolovely: As a woman you shouldn't...  
1  !!!!! RT @mleew17: boy dats cold...tyga dwn ba...  
2  !!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...  
3  !!!!!!!!! RT @C_G_Anderson: @viva_based she lo...  
4  !!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...

In [77]:
#NLP cleaning
tweets = []
tweet = hsdata['tweet'].tolist()
wordnet = WordNetLemmatizer()
i = 0
for twee in tweet:
    no_num = re.sub('[^a-zA-Z]', ' ', twee)
    lower_case = no_num.lower()
    listofwords = lower_case.split()
    after_lemat = [wordnet.lemmatize(word) for word in listofwords if word not in stopwords.words('english')]
    review = ' '.join(after_lemat)
    tweets.append(review)

In [90]:
tfidf = TfidfVectorizer(max_features=500)
X = tfidf.fit_transform(tweets)
y = hsdata['class']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [91]:
mnb = MultinomialNB()
mnb.fit(X_train, y_train)

MultinomialNB()

In [92]:
y_pred = mnb.predict(X_test)

In [93]:
cm = confusion_matrix(y_test, y_pred)
cr = classification_report(y_test, y_pred)
acc = accuracy_score(y_test, y_pred)

print(cm, '\n\n', cr, '\n', acc)

[[   2  350    9]
 [   0 4752   42]
 [   0  580  461]] 

               precision    recall  f1-score   support

           0       1.00      0.01      0.01       361
           1       0.84      0.99      0.91      4794
           2       0.90      0.44      0.59      1041

    accuracy                           0.84      6196
   macro avg       0.91      0.48      0.50      6196
weighted avg       0.86      0.84      0.80      6196
 
 0.841672046481601
